# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6284526a86629d63e29a8aa546c199e5b62a5897779fd61e25c27a91d1cf3308eea4e3a6a500e609f0f99ae5f211157348dff84eea3212d9b03b00cdfdeb910a

test:
  secret_key_base: a33859cfaa37fa59ab94a542dc22d46eddae048e18ec1956b8298f5efc9a44f586c7456bcee8f7c3c060483d6eb9cc42b44350edc29cc6f4a98d5c2b92ddf827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
